model_list: []

litellm_settings:
  drop_params: true
  success_callback: []
  failure_callback: []
  default_openai_organization: os.environ/OPENAI_ORG_ID

general_settings:
  store_model_in_db: true
  store_prompts_in_spend_logs: true
  master_key: os.environ/LITELLM_MASTER_KEY
  database_url: os.environ/DATABASE_URL
  custom_auth: custom_auth.user_api_key_auth
  pass_through_endpoints:
    - path: /claude
      target: https://api.anthropic.com
      auth: false
      forward_headers: true
    - path: /codex
      target: https://api.openai.com/v1
      auth: false
      forward_headers: true
